.TH webchanges 3.0.0-beta.2 "1" Manual
.SH NAME
webchanges 3.0.0-beta.2
.SH SYNOPSIS
.B webchanges
monitors webpages for you
.SH DESCRIPTION
webchanges watches webpages (or the output of local commands) for
changes, and notifies you via e\-mail or one of many other supported
services if one is detected. The notification includes the changed URL
or command and a summary of what has changed.
.SH OPTIONS

.TP
\fB\-V\fR, \fB\-\-version\fR
show program's version number and exit

.TP
\fB\-v\fR, \fB\-\-verbose\fR
show debug output

.TP
\fB\-\-jobs\fR FILE, \fB\-\-urls\fR FILE
read job list (URLs) from FILE

.TP
\fB\-\-config\fR FILE
read configuration from FILE

.TP
\fB\-\-hooks\fR FILE
use FILE as hooks.py module

.TP
\fB\-\-cache\fR FILE
use FILE as cache database, alternatively can accept a redis URI

.TP
\fB\-\-list\fR
list jobs

.TP
\fB\-\-test\fR JOB, \fB\-\-test\-filter\fR JOB
test filter output of job by location or index

.TP
\fB\-\-test\-diff\fR JOB, \fB\-\-test\-diff\-filter\fR JOB
test diff filter output of job by location or index (needs at least 2 snapshots)

.TP
\fB\-\-errors\fR
list jobs with errors or no data captured

.TP
\fB\-\-add\fR JOB
add job (key1=value1,key2=value2,...) (obsolete; use \-\-edit)

.TP
\fB\-\-delete\fR JOB
delete job by location or index (obsolete; use \-\-edit)

.TP
\fB\-\-test\-reporter\fR REPORTER
Send a test notification

.TP
\fB\-\-smtp\-login\fR
Check SMTP login

.TP
\fB\-\-telegram\-chats\fR
List telegram chats the bot is joined to

.TP
\fB\-\-xmpp\-login\fR
Enter password for XMPP (store in keyring)

.TP
\fB\-\-edit\fR
edit URL/job list

.TP
\fB\-\-edit\-config\fR
edit configuration file

.TP
\fB\-\-edit\-hooks\fR
edit hooks script

.TP
\fB\-\-gc\-cache\fR
remove old cache entries (snapshots)

.TP
\fB\-\-features\fR
list supported job types, filters and reporters

    .TP
    .B $XDG_CONFIG_HOME/webchanges/jobs.yaml
    A list of URLs, commands and other jobs to watch
    
    .TP
    .B $XDG_CONFIG_HOME/webchanges/config.py
    Options for the program, including methods of notification
    
    .TP
    .B $XDG_CONFIG_HOME/webchanges/hooks.py
    A Python module that can implement new job types, filters and reporters
    
    .TP
    .B $XDG_CACHE_HOME/webchanges/cache.db
    A SQLite 3 database that contains the state history of jobs (for diffing)
    
    .SH AUTHOR
    Mike Borsetti
    
    .SH WEBSITE
    https://github.com/mborsetti/webchanges
    