"""Storage: jobs files, config files, hooks file, and cache database engines."""

# The code below is subject to the license contained in the LICENSE file, with the exception of the
# the SOURCE CODE REDISTRIBUTION NOTICE since this code does not include any redistributed code.

from webchanges.storage._base import (
    BaseFileStorage,
    BaseStorage,
    BaseTextualFileStorage,
    BaseYamlFileStorage,
    JobsBaseFileStorage,
)
from webchanges.storage._config import (
    DEFAULT_CONFIG,
    _Config,
    _ConfigDatabase,
    _ConfigDifferDefaults,
    _ConfigDisplay,
    _ConfigJobDefaults,
    _ConfigReport,
    _ConfigReportBrowser,
    _ConfigReportDiscord,
    _ConfigReportEmail,
    _ConfigReportEmailSendmail,
    _ConfigReportEmailSmtp,
    _ConfigReportGithubIssue,
    _ConfigReportGotify,
    _ConfigReportHtml,
    _ConfigReportIfttt,
    _ConfigReportMailgun,
    _ConfigReportMarkdown,
    _ConfigReportMatrix,
    _ConfigReportNtfy,
    _ConfigReportNtfyPriorities,
    _ConfigReportProwl,
    _ConfigReportPushbullet,
    _ConfigReportPushover,
    _ConfigReportRunCommand,
    _ConfigReportStdout,
    _ConfigReportTelegram,
    _ConfigReportText,
    _ConfigReportWebhook,
    _ConfigReportXmpp,
)
from webchanges.storage._redis import SsdbRedisStorage
from webchanges.storage._sqlite3 import SsdbSQLite3Storage
from webchanges.storage._ssdb import SsdbDirStorage, SsdbStorage
from webchanges.storage._yaml import YamlConfigStorage, YamlJobsStorage

__all__ = [
    'DEFAULT_CONFIG',
    'BaseFileStorage',
    'BaseStorage',
    'BaseTextualFileStorage',
    'BaseYamlFileStorage',
    'JobsBaseFileStorage',
    'SsdbDirStorage',
    'SsdbRedisStorage',
    'SsdbSQLite3Storage',
    'SsdbStorage',
    'YamlConfigStorage',
    'YamlJobsStorage',
    '_Config',
    '_ConfigDatabase',
    '_ConfigDifferDefaults',
    '_ConfigDisplay',
    '_ConfigJobDefaults',
    '_ConfigReport',
    '_ConfigReportBrowser',
    '_ConfigReportDiscord',
    '_ConfigReportEmail',
    '_ConfigReportEmailSendmail',
    '_ConfigReportEmailSmtp',
    '_ConfigReportGithubIssue',
    '_ConfigReportGotify',
    '_ConfigReportHtml',
    '_ConfigReportIfttt',
    '_ConfigReportMailgun',
    '_ConfigReportMarkdown',
    '_ConfigReportMatrix',
    '_ConfigReportNtfy',
    '_ConfigReportNtfyPriorities',
    '_ConfigReportProwl',
    '_ConfigReportPushbullet',
    '_ConfigReportPushover',
    '_ConfigReportRunCommand',
    '_ConfigReportStdout',
    '_ConfigReportTelegram',
    '_ConfigReportText',
    '_ConfigReportWebhook',
    '_ConfigReportXmpp',
]
