"""Filters."""

# The code below is subject to the license contained in the LICENSE file, with the exception of the
# the SOURCE CODE REDISTRIBUTION NOTICE since this code does not include any redistributed code.

from webchanges.filters._base import AutoMatchFilter, FilterBase, RegexMatchFilter
from webchanges.filters._document import (
    Csv2TextFilter,
    FormatJsonFilter,
    Ical2TextFilter,
    JQFilter,
    JsontoYamlFilter,
    OCRFilter,
    Pdf2TextFilter,
    PypdfFilter,
)
from webchanges.filters._encoding import Ascii85, Base64, HexDumpFilter, Sha1SumFilter, Sha256SumFilter
from webchanges.filters._html import (
    AbsoluteLinksFilter,
    BeautifyFilter,
    CSSFilter,
    ElementByClassFilter,
    ElementByIdFilter,
    ElementByStyleFilter,
    ElementByTagFilter,
    ElementsBy,
    FilterBy,
    FormatXMLFilter,
    Html2TextFilter,
    LxmlParser,
    PrettyXMLFilter,
    XPathFilter,
)
from webchanges.filters._shell import ExecuteFilter, ShellPipeFilter
from webchanges.filters._text import (
    DeleteLinesContainingFilter,
    GrepFilter,
    GrepIFilter,
    KeepLinesContainingFilter,
    RegexFindall,
    RemoveDuplicateLinesFilter,
    RemoveRepeatedFilter,
    ReSubFilter,
    ReverseFilter,
    SortFilter,
    StripFilter,
    StripLinesFilter,
)

__all__ = [
    'AbsoluteLinksFilter',
    'Ascii85',
    'AutoMatchFilter',
    'Base64',
    'BeautifyFilter',
    'CSSFilter',
    'Csv2TextFilter',
    'DeleteLinesContainingFilter',
    'ElementByClassFilter',
    'ElementByIdFilter',
    'ElementByStyleFilter',
    'ElementByTagFilter',
    'ElementsBy',
    'ExecuteFilter',
    'FilterBase',
    'FilterBy',
    'FormatJsonFilter',
    'FormatXMLFilter',
    'GrepFilter',
    'GrepIFilter',
    'HexDumpFilter',
    'Html2TextFilter',
    'Ical2TextFilter',
    'JQFilter',
    'JsontoYamlFilter',
    'KeepLinesContainingFilter',
    'LxmlParser',
    'OCRFilter',
    'Pdf2TextFilter',
    'PrettyXMLFilter',
    'PypdfFilter',
    'ReSubFilter',
    'RegexFindall',
    'RegexMatchFilter',
    'RemoveDuplicateLinesFilter',
    'RemoveRepeatedFilter',
    'ReverseFilter',
    'Sha1SumFilter',
    'Sha256SumFilter',
    'ShellPipeFilter',
    'SortFilter',
    'StripFilter',
    'StripLinesFilter',
    'XPathFilter',
]
